#ifndef GovSteamFV4_H
#define GovSteamFV4_H
/*
Generated from the CGMES files via cimgen: https://github.com/sogno-platform/cimgen
*/

#include <list>
#include <map>
#include <string>
#include <unordered_map>

#include "TurbineGovernorDynamics.hpp"
#include "BaseClassDefiner.hpp"
#include "CGMESProfile.hpp"
#include "CimClassDetails.hpp"

#include "Float.hpp"
#include "PU.hpp"
#include "Seconds.hpp"

namespace CIMPP
{

	/** \brief Detailed electro-hydraulic governor for steam unit. */
	class GovSteamFV4 : public TurbineGovernorDynamics
	{
	public:
		/* constructor initialising all attributes to null */
		GovSteamFV4();
		~GovSteamFV4() override;

		/** \brief Minimum value of pressure regulator output (<i>Cpsmn</i>).  Typical value = -1. Default: 0.0 */
		CIMPP::PU cpsmn;

		/** \brief Maximum value of pressure regulator output (<i>Cpsmx</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU cpsmx;

		/** \brief Minimum value of regulator set-point (<i>Crmn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU crmn;

		/** \brief Maximum value of regulator set-point (<i>Crmx</i>).  Typical value = 1,2. Default: 0.0 */
		CIMPP::PU crmx;

		/** \brief Derivative gain of pressure regulator (<i>Kdc</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU kdc;

		/** \brief Frequency bias (reciprocal of droop) (<i>Kf1</i>).  Typical value = 20. Default: 0.0 */
		CIMPP::PU kf1;

		/** \brief Frequency control (reciprocal of droop) (<i>Kf3</i>).  Typical value = 20. Default: 0.0 */
		CIMPP::PU kf3;

		/** \brief Fraction  of total turbine output generated by HP part (<i>Khp</i>).  Typical value = 0,35. Default: 0.0 */
		CIMPP::PU khp;

		/** \brief Integral gain of pressure regulator (<i>Kic</i>).  Typical value = 0,0033. Default: 0.0 */
		CIMPP::PU kic;

		/** \brief Integral gain of pressure feedback regulator (<i>Kip</i>).  Typical value = 0,5. Default: 0.0 */
		CIMPP::PU kip;

		/** \brief Integral gain of electro-hydraulic regulator (<i>Kit</i>).  Typical value = 0,04. Default: 0.0 */
		CIMPP::PU kit;

		/** \brief First gain coefficient of  intercept valves characteristic (<i>Kmp1</i>).  Typical value = 0,5. Default: 0.0 */
		CIMPP::PU kmp1;

		/** \brief Second gain coefficient of intercept valves characteristic (<i>Kmp2</i>).  Typical value = 3,5. Default: 0.0 */
		CIMPP::PU kmp2;

		/** \brief Proportional gain of pressure regulator (<i>Kpc</i>).  Typical value = 0,5. Default: 0.0 */
		CIMPP::PU kpc;

		/** \brief Proportional gain of pressure feedback regulator (<i>Kpp</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU kpp;

		/** \brief Proportional gain of electro-hydraulic regulator (<i>Kpt</i>).  Typical value = 0,3. Default: 0.0 */
		CIMPP::PU kpt;

		/** \brief Maximum variation of fuel flow (<i>Krc</i>).  Typical value = 0,05. Default: 0.0 */
		CIMPP::PU krc;

		/** \brief Pressure loss due to flow friction in the boiler tubes (<i>Ksh</i>).  Typical value = 0,08. Default: 0.0 */
		CIMPP::PU ksh;

		/** \brief Maximum negative power error (<i>Lpi</i>).  Typical value = -0,15. Default: 0.0 */
		CIMPP::PU lpi;

		/** \brief Maximum positive power error (<i>Lps</i>).  Typical value = 0,03. Default: 0.0 */
		CIMPP::PU lps;

		/** \brief Lower limit for frequency correction (<i>MN</i><i><sub>EF</sub></i>).  Typical value = -0,05. Default: 0.0 */
		CIMPP::PU mnef;

		/** \brief Upper limit for frequency correction (<i>MX</i><i><sub>EF</sub></i>).  Typical value = 0,05. Default: 0.0 */
		CIMPP::PU mxef;

		/** \brief First value of pressure set point static characteristic (<i>Pr1</i>).  Typical value = 0,2. Default: 0.0 */
		CIMPP::PU pr1;

		/** \brief Second value of pressure set point static characteristic, corresponding to <i>Ps0</i> = 1,0 PU (<i>Pr2</i>).  Typical value = 0,75. Default: 0.0 */
		CIMPP::PU pr2;

		/** \brief Minimum value of pressure set point static characteristic (<i>Psmn</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU psmn;

		/** \brief Minimum value of integral regulator (<i>Rsmimn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU rsmimn;

		/** \brief Maximum value of integral regulator (<i>Rsmimx</i>).  Typical value = 1,1. Default: 0.0 */
		CIMPP::PU rsmimx;

		/** \brief Minimum value of integral regulator (<i>Rvgmn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU rvgmn;

		/** \brief Maximum value of integral regulator (<i>Rvgmx</i>).  Typical value = 1,2. Default: 0.0 */
		CIMPP::PU rvgmx;

		/** \brief Minimum valve opening (<i>Srmn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU srmn;

		/** \brief Maximum valve opening (<i>Srmx</i>).  Typical value = 1,1. Default: 0.0 */
		CIMPP::PU srmx;

		/** \brief Intercept valves characteristic discontinuity point (<i>Srsmp</i>).  Typical value = 0,43. Default: 0.0 */
		CIMPP::PU srsmp;

		/** \brief Maximum regulator gate closing velocity (<i>Svmn</i>).  Typical value = -0,0333. Default: 0.0 */
		CIMPP::Float svmn;

		/** \brief Maximum regulator gate opening velocity (<i>Svmx</i>).  Typical value = 0,0333. Default: 0.0 */
		CIMPP::Float svmx;

		/** \brief Control valves rate opening time (<i>Ta</i>) (&gt;= 0).  Typical value = 0,8. Default: 0.0 */
		CIMPP::Seconds ta;

		/** \brief Intercept valves rate opening time (<i>Tam</i>) (&gt;= 0).  Typical value = 0,8. Default: 0.0 */
		CIMPP::Seconds tam;

		/** \brief Control valves rate closing time (<i>Tc</i>) (&gt;= 0).  Typical value = 0,5. Default: 0.0 */
		CIMPP::Seconds tc;

		/** \brief Intercept valves rate closing time (<i>Tcm</i>) (&gt;= 0).  Typical value = 0,5. Default: 0.0 */
		CIMPP::Seconds tcm;

		/** \brief Derivative time constant of pressure regulator (<i>Tdc</i>) (&gt;= 0).  Typical value = 90. Default: 0.0 */
		CIMPP::Seconds tdc;

		/** \brief Time constant of fuel regulation (<i>Tf1</i>) (&gt;= 0).  Typical value = 10. Default: 0.0 */
		CIMPP::Seconds tf1;

		/** \brief Time constant of steam chest (<i>Tf2</i>) (&gt;= 0).  Typical value = 10. Default: 0.0 */
		CIMPP::Seconds tf2;

		/** \brief High pressure (HP) time constant of the turbine (<i>Thp</i>) (&gt;= 0).  Typical value = 0,15. Default: 0.0 */
		CIMPP::Seconds thp;

		/** \brief Low pressure (LP) time constant of the turbine (<i>Tmp</i>) (&gt;= 0).  Typical value = 0,4. Default: 0.0 */
		CIMPP::Seconds tmp;

		/** \brief Reheater  time constant of the turbine (<i>Trh</i>) (&gt;= 0).  Typical value = 10. Default: 0.0 */
		CIMPP::Seconds trh;

		/** \brief Boiler time constant (<i>Tv</i>) (&gt;= 0).  Typical value = 60. Default: 0.0 */
		CIMPP::Seconds tv;

		/** \brief Control valves servo time constant (<i>Ty</i>) (&gt;= 0).  Typical value = 0,1. Default: 0.0 */
		CIMPP::Seconds ty;

		/** \brief Coefficient of linearized equations of turbine (Stodola formulation) (<i>Y</i>).  Typical value = 0,13. Default: 0.0 */
		CIMPP::PU y;

		/** \brief Minimum control valve position (<i>Yhpmn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU yhpmn;

		/** \brief Maximum control valve position (<i>Yhpmx</i>).  Typical value = 1,1. Default: 0.0 */
		CIMPP::PU yhpmx;

		/** \brief Minimum intercept valve position (<i>Ympmn</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU ympmn;

		/** \brief Maximum intercept valve position (<i>Ympmx</i>).  Typical value = 1,1. Default: 0.0 */
		CIMPP::PU ympmx;

		static const char debugName[];
		const char* debugString() const override;

		const std::list<std::string>& getAttributeNames() const override;

		const std::string& getClassNamespaceUrl() const override;
		const std::string& getAttributeNamespaceUrl(const std::string& attrName) const override;

		const std::list<CGMESProfile>& getPossibleProfiles() const override;
		const CGMESProfile& getRecommendedProfile() const override;
		const std::list<CGMESProfile>& getPossibleAttributeProfiles(const std::string& attrName) const override;
		const std::list<CGMESProfile>& getPossibleProfilesIncludingAttributes() const override;

		static void addConstructToMap(std::unordered_map<std::string, BaseClass* (*)()>& factory_map);
		static void addPrimitiveAssignFnsToMap(std::unordered_map<std::string, assign_function>& assign_map);
		static void addClassAssignFnsToMap(std::unordered_map<std::string, class_assign_function>& assign_map);
		void addPrimitiveGetFnsToMap(std::map<std::string, get_function>& get_map) const override;
		void addClassGetFnsToMap(std::map<std::string, class_get_function>& get_map) const override;
		void addEnumGetFnsToMap(std::map<std::string, get_function>& get_map) const override;

		bool isAssignableFrom(BaseClass* otherObject) const override;
		static const BaseClassDefiner declare();

	protected:
		std::map<std::string, AttrDetails> allAttrDetailsMap() const override;
	};

	BaseClass* GovSteamFV4_factory();
}
#endif
