#ifndef GovSteamEU_H
#define GovSteamEU_H
/*
Generated from the CGMES files via cimgen: https://github.com/sogno-platform/cimgen
*/

#include <list>
#include <map>
#include <string>
#include <unordered_map>

#include "TurbineGovernorDynamics.hpp"
#include "BaseClassDefiner.hpp"
#include "CGMESProfile.hpp"
#include "CimClassDetails.hpp"

#include "ActivePower.hpp"
#include "Float.hpp"
#include "PU.hpp"
#include "Seconds.hpp"

namespace CIMPP
{

	/** \brief Simplified boiler and steam turbine with PID governor. */
	class GovSteamEU : public TurbineGovernorDynamics
	{
	public:
		/* constructor initialising all attributes to null */
		GovSteamEU();
		~GovSteamEU() override;

		/** \brief Control valves rate closing limit (<i>Chc</i>).  Unit = PU / s.  Typical value = -3,3. Default: 0.0 */
		CIMPP::Float chc;

		/** \brief Control valves rate opening limit (<i>Cho</i>).  Unit = PU / s.  Typical value = 0,17. Default: 0.0 */
		CIMPP::Float cho;

		/** \brief Intercept valves rate closing limit (<i>Cic</i>).  Typical value = -2,2. Default: 0.0 */
		CIMPP::PU cic;

		/** \brief Intercept valves rate opening limit (<i>Cio</i>).  Typical value = 0,123. Default: 0.0 */
		CIMPP::PU cio;

		/** \brief Deadband of the frequency corrector (<i>db1</i>).  Typical value = 0. Default: 0.0 */
		CIMPP::PU db1;

		/** \brief Deadband of the speed governor (<i>db2</i>).  Typical value = 0,0004. Default: 0.0 */
		CIMPP::PU db2;

		/** \brief Maximum control valve position (<i>Hhpmax</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU hhpmax;

		/** \brief Gain of the power controller (<i>Ke</i>).  Typical value = 0,65. Default: 0.0 */
		CIMPP::PU ke;

		/** \brief Gain of the frequency corrector (<i>Kfcor</i>).  Typical value = 20. Default: 0.0 */
		CIMPP::PU kfcor;

		/** \brief Fraction of total turbine output generated by HP part (<i>Khp</i>).  Typical value = 0,277. Default: 0.0 */
		CIMPP::PU khp;

		/** \brief Fraction of total turbine output generated by HP part (<i>Klp</i>).  Typical value = 0,723. Default: 0.0 */
		CIMPP::PU klp;

		/** \brief Gain of the speed governor (<i>Kwcor</i>).  Typical value = 20. Default: 0.0 */
		CIMPP::PU komegacor;

		/** \brief Base for power values (<i>MWbase</i>) (&gt; 0).  Unit = MW. Default: 0.0 */
		CIMPP::ActivePower mwbase;

		/** \brief Maximal active power of the turbine (<i>Pmax</i>).  Typical value = 1. Default: 0.0 */
		CIMPP::PU pmax;

		/** \brief Maximum low pressure limit (<i>Prhmax</i>).  Typical value = 1,4. Default: 0.0 */
		CIMPP::PU prhmax;

		/** \brief Intercept valves transfer limit (<i>Simx</i>).  Typical value = 0,425. Default: 0.0 */
		CIMPP::PU simx;

		/** \brief Boiler time constant (<i>Tb</i>) (&gt;= 0).  Typical value = 100. Default: 0.0 */
		CIMPP::Seconds tb;

		/** \brief Derivative time constant of the power controller (<i>Tdp</i>) (&gt;= 0).  Typical value = 0. Default: 0.0 */
		CIMPP::Seconds tdp;

		/** \brief Electro hydraulic transducer (<i>Ten</i>) (&gt;= 0).  Typical value = 0,1. Default: 0.0 */
		CIMPP::Seconds ten;

		/** \brief Frequency transducer time constant (<i>Tf</i>) (&gt;= 0).  Typical value = 0. Default: 0.0 */
		CIMPP::Seconds tf;

		/** \brief Time constant of the power controller (<i>Tfp</i>) (&gt;= 0).  Typical value = 0. Default: 0.0 */
		CIMPP::Seconds tfp;

		/** \brief High pressure (HP) time constant of the turbine (<i>Thp</i>) (&gt;= 0).  Typical value = 0,31. Default: 0.0 */
		CIMPP::Seconds thp;

		/** \brief Integral time constant of the power controller (<i>Tip</i>) (&gt;= 0).  Typical value = 2. Default: 0.0 */
		CIMPP::Seconds tip;

		/** \brief Low pressure (LP) time constant of the turbine (<i>Tlp</i>) (&gt;= 0).  Typical value = 0,45. Default: 0.0 */
		CIMPP::Seconds tlp;

		/** \brief Power transducer time constant (<i>Tp</i>) (&gt;= 0).  Typical value = 0,07. Default: 0.0 */
		CIMPP::Seconds tp;

		/** \brief Reheater  time constant of the turbine (<i>Trh</i>) (&gt;= 0).  Typical value = 8. Default: 0.0 */
		CIMPP::Seconds trh;

		/** \brief Control valves servo time constant (<i>Tvhp</i>) (&gt;= 0).  Typical value = 0,1. Default: 0.0 */
		CIMPP::Seconds tvhp;

		/** \brief Intercept valves servo time constant (<i>Tvip</i>) (&gt;= 0).  Typical value = 0,15. Default: 0.0 */
		CIMPP::Seconds tvip;

		/** \brief Speed transducer time constant (<i>Tw</i>) (&gt;= 0).  Typical value = 0,02. Default: 0.0 */
		CIMPP::Seconds tw;

		/** \brief Upper limit for frequency correction (<i>Wfmax</i>) (&gt; GovSteamEU.wfmin).  Typical value = 0,05. Default: 0.0 */
		CIMPP::PU wfmax;

		/** \brief Lower limit for frequency correction (<i>Wfmin</i>) (&lt; GovSteamEU.wfmax).  Typical value = -0,05. Default: 0.0 */
		CIMPP::PU wfmin;

		/** \brief Emergency speed control lower limit (<i>wmax1</i>).  Typical value = 1,025. Default: 0.0 */
		CIMPP::PU wmax1;

		/** \brief Emergency speed control upper limit (<i>wmax2</i>).  Typical value = 1,05. Default: 0.0 */
		CIMPP::PU wmax2;

		/** \brief Upper limit for the speed governor (<i>Wwmax</i>) (&gt; GovSteamEU.wwmin).  Typical value = 0,1. Default: 0.0 */
		CIMPP::PU wwmax;

		/** \brief Lower limit for the speed governor frequency correction (<i>Wwmin</i>) (&lt; GovSteamEU.wwmax).  Typical value = -1. Default: 0.0 */
		CIMPP::PU wwmin;

		static const char debugName[];
		const char* debugString() const override;

		const std::list<std::string>& getAttributeNames() const override;

		const std::string& getClassNamespaceUrl() const override;
		const std::string& getAttributeNamespaceUrl(const std::string& attrName) const override;

		const std::list<CGMESProfile>& getPossibleProfiles() const override;
		const CGMESProfile& getRecommendedProfile() const override;
		const std::list<CGMESProfile>& getPossibleAttributeProfiles(const std::string& attrName) const override;
		const std::list<CGMESProfile>& getPossibleProfilesIncludingAttributes() const override;

		static void addConstructToMap(std::unordered_map<std::string, BaseClass* (*)()>& factory_map);
		static void addPrimitiveAssignFnsToMap(std::unordered_map<std::string, assign_function>& assign_map);
		static void addClassAssignFnsToMap(std::unordered_map<std::string, class_assign_function>& assign_map);
		void addPrimitiveGetFnsToMap(std::map<std::string, get_function>& get_map) const override;
		void addClassGetFnsToMap(std::map<std::string, class_get_function>& get_map) const override;
		void addEnumGetFnsToMap(std::map<std::string, get_function>& get_map) const override;

		bool isAssignableFrom(BaseClass* otherObject) const override;
		static const BaseClassDefiner declare();

	protected:
		std::map<std::string, AttrDetails> allAttrDetailsMap() const override;
	};

	BaseClass* GovSteamEU_factory();
}
#endif
