name: Build & Test on Linux

on: push

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
        - CGMES_2.4.13_18DEC2013
        - CGMES_2.4.15_16FEB2016
        - CGMES_2.4.15_27JAN2020
        - CGMES_3.0.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libboost-filesystem-dev libboost-system-dev libboost-test-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_${{matrix.schema}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build_${{matrix.schema}} --parallel 4

    - name: Test
      working-directory: ${{github.workspace}}/build_${{matrix.schema}}
      run: ctest --output-on-failure
